import "../styles/globals.css";
import type { Metadata } from "next";
import { Architects_Daughter } from "next/font/google";
import Navbar from "@/components/custom/navbar";

const architectsDaughter = Architects_Daughter({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-sans",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className="max-w-3xl mx-auto min-h-svh px-2 xl:px-0">
        <Navbar />
        {children}
      </body>
    </html>
  );
}
